/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface EnsAdd {}
  interface EnsAddAttributes extends StencilHTMLAttributes {}

  interface EnsDetails {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface EnsDetailsAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsList {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface EnsListAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface EnsSearchbyemail {}
  interface EnsSearchbyemailAttributes extends StencilHTMLAttributes {}

  interface EnsSearchbyname {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface EnsSearchbynameAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormAdd {}
  interface FormAddAttributes extends StencilHTMLAttributes {}

  interface FormDetails {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface FormDetailsAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormList {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface FormListAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormSearchbyname {
    'back': RouterHistory;
    'match': MatchResults;
  }
  interface FormSearchbynameAttributes extends StencilHTMLAttributes {
    'back'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'EnsAdd': Components.EnsAdd;
    'EnsDetails': Components.EnsDetails;
    'EnsList': Components.EnsList;
    'EnsSearchbyemail': Components.EnsSearchbyemail;
    'EnsSearchbyname': Components.EnsSearchbyname;
    'FormAdd': Components.FormAdd;
    'FormDetails': Components.FormDetails;
    'FormList': Components.FormList;
    'FormSearchbyname': Components.FormSearchbyname;
    'SpiHeader': Components.SpiHeader;
    'SpiHome': Components.SpiHome;
    'SpiRoot': Components.SpiRoot;
  }

  interface StencilIntrinsicElements {
    'ens-add': Components.EnsAddAttributes;
    'ens-details': Components.EnsDetailsAttributes;
    'ens-list': Components.EnsListAttributes;
    'ens-searchbyemail': Components.EnsSearchbyemailAttributes;
    'ens-searchbyname': Components.EnsSearchbynameAttributes;
    'form-add': Components.FormAddAttributes;
    'form-details': Components.FormDetailsAttributes;
    'form-list': Components.FormListAttributes;
    'form-searchbyname': Components.FormSearchbynameAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-root': Components.SpiRootAttributes;
  }


  interface HTMLEnsAddElement extends Components.EnsAdd, HTMLStencilElement {}
  var HTMLEnsAddElement: {
    prototype: HTMLEnsAddElement;
    new (): HTMLEnsAddElement;
  };

  interface HTMLEnsDetailsElement extends Components.EnsDetails, HTMLStencilElement {}
  var HTMLEnsDetailsElement: {
    prototype: HTMLEnsDetailsElement;
    new (): HTMLEnsDetailsElement;
  };

  interface HTMLEnsListElement extends Components.EnsList, HTMLStencilElement {}
  var HTMLEnsListElement: {
    prototype: HTMLEnsListElement;
    new (): HTMLEnsListElement;
  };

  interface HTMLEnsSearchbyemailElement extends Components.EnsSearchbyemail, HTMLStencilElement {}
  var HTMLEnsSearchbyemailElement: {
    prototype: HTMLEnsSearchbyemailElement;
    new (): HTMLEnsSearchbyemailElement;
  };

  interface HTMLEnsSearchbynameElement extends Components.EnsSearchbyname, HTMLStencilElement {}
  var HTMLEnsSearchbynameElement: {
    prototype: HTMLEnsSearchbynameElement;
    new (): HTMLEnsSearchbynameElement;
  };

  interface HTMLFormAddElement extends Components.FormAdd, HTMLStencilElement {}
  var HTMLFormAddElement: {
    prototype: HTMLFormAddElement;
    new (): HTMLFormAddElement;
  };

  interface HTMLFormDetailsElement extends Components.FormDetails, HTMLStencilElement {}
  var HTMLFormDetailsElement: {
    prototype: HTMLFormDetailsElement;
    new (): HTMLFormDetailsElement;
  };

  interface HTMLFormListElement extends Components.FormList, HTMLStencilElement {}
  var HTMLFormListElement: {
    prototype: HTMLFormListElement;
    new (): HTMLFormListElement;
  };

  interface HTMLFormSearchbynameElement extends Components.FormSearchbyname, HTMLStencilElement {}
  var HTMLFormSearchbynameElement: {
    prototype: HTMLFormSearchbynameElement;
    new (): HTMLFormSearchbynameElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLElementTagNameMap {
    'ens-add': HTMLEnsAddElement
    'ens-details': HTMLEnsDetailsElement
    'ens-list': HTMLEnsListElement
    'ens-searchbyemail': HTMLEnsSearchbyemailElement
    'ens-searchbyname': HTMLEnsSearchbynameElement
    'form-add': HTMLFormAddElement
    'form-details': HTMLFormDetailsElement
    'form-list': HTMLFormListElement
    'form-searchbyname': HTMLFormSearchbynameElement
    'spi-header': HTMLSpiHeaderElement
    'spi-home': HTMLSpiHomeElement
    'spi-root': HTMLSpiRootElement
  }

  interface ElementTagNameMap {
    'ens-add': HTMLEnsAddElement;
    'ens-details': HTMLEnsDetailsElement;
    'ens-list': HTMLEnsListElement;
    'ens-searchbyemail': HTMLEnsSearchbyemailElement;
    'ens-searchbyname': HTMLEnsSearchbynameElement;
    'form-add': HTMLFormAddElement;
    'form-details': HTMLFormDetailsElement;
    'form-list': HTMLFormListElement;
    'form-searchbyname': HTMLFormSearchbynameElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-root': HTMLSpiRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
